name: Restore build and run the tests

on:
  push:
    branches:
      - develop 
      - feature 
      
jobs:
  restore_build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build the project
      run: dotnet build --no-restore
    - name: Run all tests
      run: dotnet test --no-build --verbosity normal
